export enum StoringProperty {
    USER_INFO = 'USER_INFO',
    ACCESS_TOKEN = 'ACCESS_TOKEN',
    REFRESH_TOKEN = 'REFRESH_TOKEN',
    USER_CONFIGURATION = 'USER_CONFIGURATION',
    GENERAL_CONFIGURATION = 'GENERAL_CONFIGURATION',
  }